### ISSUE TITLE
Incorrect repo in readme.md?

### ISSUE THREAD

**Issue by p-mohan** [uclnlp/stat-nlp-book-scala#6]
Shouldn't it be git clone https://github.com/uclmr/stat-nlp-book-scala.git instead of git clone https://github.com/uclmr/stat-nlp-book.git?

**Comment by riedelcastro** [comment]
Thanks, I fixed that. But note that `stat-nlp-book-scala` is deprecated and effectively replaced by the python version:

https://github.com/uclmr/stat-nlp-book

**Comment by p-mohan** [comment]
Thanks!
